# Generated by Django 4.1.5 on 2023-01-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес компании')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон компании')),
                ('code_company', models.IntegerField(validators=[main.models.validate_int])),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('boss', models.CharField(max_length=255, verbose_name='Управляющий')),
                ('number_storage', models.IntegerField(validators=[main.models.validate_int])),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название акции')),
                ('company', models.CharField(max_length=25, verbose_name='Название компании')),
                ('price', models.IntegerField(validators=[main.models.validate_price], verbose_name='Прайс')),
                ('number', models.IntegerField(validators=[main.models.validate_int])),
                ('photo', models.CharField(max_length=300, verbose_name='Фото акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('code_sale', models.IntegerField(validators=[main.models.validate_int])),
                ('number_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='main.storages')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('sale_date', models.DateTimeField()),
                ('artist', models.IntegerField(validators=[main.models.validate_int])),
                ('code_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main', to='main.companies', verbose_name='Компания')),
                ('code_sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main', to='main.sales', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Главная',
                'verbose_name_plural': 'Главная',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStorages',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('boss', models.CharField(max_length=255, verbose_name='Управляющий')),
                ('number_storage', models.IntegerField(validators=[main.models.validate_int])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Место хранения',
                'verbose_name_plural': 'historical Места хранения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSales',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название акции')),
                ('company', models.CharField(max_length=25, verbose_name='Название компании')),
                ('price', models.IntegerField(validators=[main.models.validate_price], verbose_name='Прайс')),
                ('number', models.IntegerField(validators=[main.models.validate_int])),
                ('photo', models.CharField(max_length=300, verbose_name='Фото акции')),
                ('description', models.TextField(verbose_name='Описание акции')),
                ('code_sale', models.IntegerField(validators=[main.models.validate_int])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('number_storage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.storages')),
            ],
            options={
                'verbose_name': 'historical Акция',
                'verbose_name_plural': 'historical Акции',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMain',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sale', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('sale_date', models.DateTimeField()),
                ('artist', models.IntegerField(validators=[main.models.validate_int])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('code_company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.companies', verbose_name='Компания')),
                ('code_sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.sales', verbose_name='Акция')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Главная',
                'verbose_name_plural': 'historical Главная',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContacts',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code_assistant', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес представителя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон представителя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('code_company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.companies')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Контакт',
                'verbose_name_plural': 'historical Контакты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompanies',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес компании')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон компании')),
                ('code_company', models.IntegerField(validators=[main.models.validate_int])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Компания',
                'verbose_name_plural': 'historical Компании',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_assistant', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес представителя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон представителя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('code_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='сontacts', to='main.companies')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(to='main.sales', verbose_name='Любимые акции'),
        ),
    ]
